baseurl = "https://mailsquad.com/en/"
publishdir = "../../html/en"
staticdir = "../static"
canonifyurls = false

title = "Email marketing solution for agencies"

[[menu.top]]
	name = "Features"
	identifier = "features"
	url = "/features"
	weight = 1
[[menu.top]]
	name = "Pricing"
	identifier = "pricing"
	url = "/pricing"
	weight = 2
[[menu.top]]
	name = "Contact"
	identifier = "contact"
	url = "/contact"
	weight = 3
[[menu.top]]
	name = "Support"
	identifier = "support"
	url = "http://help.mailsquad.com"
	weight = 4

[[menu.topreseller]]
	name = "Reseller Features"
	identifier = "features"
	url = "/reseller/features"
	weight = 1
[[menu.topreseller]]
	name = "Reseller Pricing"
	identifier = "pricing"
	url = "/reseller/pricing"
	weight = 2
[[menu.topreseller]]
	name = "Contact"
	identifier = "contact"
	url = "/contact"
	weight = 3
[[menu.topreseller]]
	name = "Support"
	identifier = "support"
	url = "http://help.mailsquad.com"
	weight = 4