baseurl = "https://mailsquad.com/fr/"
publishdir = "../../html/fr"
staticdir = "../static"
canonifyurls = false

title = "Marketing email pour les agences et professionnels du Web"

[permalinks]
  blogue = "/blogue/:year/:month/:slug/"
[[menu.top]]
	name = "Fonctionnalités"
	identifier = "features"
	url = "/fonctionnalites"
	weight = 1
[[menu.top]]
	name = "Tarifs"
	identifier = "prix"
	url = "/tarifs"
	weight = 2
[[menu.top]]
	name = "Contact"
	identifier = "contact"
	url = "/contact"
	weight = 3
[[menu.top]]
	name = "Support"
	identifier = "support"
	url = "/support"
	weight = 4
[[menu.top]]
	name = "Blogue"
	identifier = "blogue"
	url = "/blogue"
	weight = 5

[[menu.topreseller]]
	name = "Fonctionnalités Revendeur"
	identifier = "features"
	url = "/revendeur/fonctionnalites"
	weight = 1
[[menu.topreseller]]
	name = "Tarif revendeur"
	identifier = "pricing"
	url = "/revendeur/tarifs"
	weight = 2
[[menu.topreseller]]
	name = "Contact"
	identifier = "contact"
	url = "/contact"
	weight = 3
[[menu.topreseller]]
	name = "Support"
	identifier = "support"
	url = "http://aide.mailsquad.com"
	weight = 4